services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8000:8000"
    env_file:
      - .env
    
    develop:
      watch:
        - path: ./requirements.txt 
          action: rebuild 
        - path: ./backend/* 
          action: rebuild 
       