version: '3'

tasks:
  venv:
    desc: make venv
    cmds:
      - bash -lc 'printf "\e[34m[setup]\e[0m creating venv\n"'
      - python3 -m venv .venv

  deps:
    desc: install deps
    cmds:
      - bash -lc 'printf "\e[34m[deps]\e[0m installing\n"'
      - .venv/bin/pip install -r ./requirements.txt

  up:
    desc: start services
    cmds:
      - bash -lc 'printf "\e[32m[up]\e[0m docker compose up\n"'
      - docker compose up

  up:watch:
    desc: start and watch
    cmd: |
      bash -lc 'printf "\e[32m[up]\e[0m watch\n"; docker compose up --watch'

  down:
    desc: stop services
    cmd: |
      bash -lc 'printf "\e[33m[down]\e[0m stopping\n"; docker compose down --remove-orphans'
  
  up-watch-build:
    desc: start and watch and build
    cmd: |
      bash -lc 'printf "\e[32m[up]\e[0m watch and build\n"; docker compose up --watch --build'

  clean:
    desc: prune containers
    cmd: |
      bash -lc 'printf "\e[31m[clean]\e[0m pruning\n"; docker system prune -f'


